---
- name: Archive Management Playbook
  hosts: localhost
  gather_facts: no
  vars:
    PIONEER_ROOT: "pioneer/nbsedev_user_DEV2/pioneer/latest"
    ARCH_DIR: "{{ PIONEER_ROOT }}/ARCH"

  tasks:
    
    - name: Ensure ARCH directory exists
      file:
        path: "{{ ARCH_DIR }}"
        state: directory

    - name: Create a new timestamped directory
      vars:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
      command: "mkdir -p {{ ARCH_DIR }}/{{ timestamp }}"
      register: new_timestamp_dir
      changed_when: new_timestamp_dir.rc == 0
      notify:
        - Set latest directory fact

    - name: Log new directory creation
      debug:
        msg: "Created new directory: {{ ARCH_DIR }}/{{ timestamp }}"

    - name: Find all timestamped directories in ARCH
      find:
        paths: "{{ ARCH_DIR }}"
        recurse: no
        file_type: directory
      register: arch_dirs

    - name: Sort directories by modification time
      set_fact:
        arch_dirs_sorted: "{{ arch_dirs.files | sort(attribute='mtime') }}"
        arch_dir_count: "{{ arch_dirs.files | length }}"

    - name: Remove oldest directories if more than 3 exist
      when: arch_dir_count > 3
      block:
        - name: Calculate directories to delete
          set_fact:
            to_delete_count: "{{ arch_dir_count - 3 }}"

        - name: Delete oldest directories to retain only the latest 3
          file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ arch_dirs_sorted | slice(to_delete_count) }}"
          loop_control:
            label: "{{ item.path }}"

    - name: Update symbolic link to the latest directory
      file:
        src: "{{ arch_dirs_sorted[-1].path }}"
        dest: "{{ ARCH_DIR }}/latest"
        state: link
        force: yes

    - name: Log symbolic link update
      debug:
        msg: "Updated symlink to point to the latest directory: {{ arch_dirs_sorted[-1].path }}"

  handlers:
    - name: Set latest directory fact
      set_fact:
        latest_dir: "{{ ARCH_DIR }}/{{ timestamp }}"
